project:
  type: book

book:
  title: "CrespiBot"
  author: "Tec. Sup. Christopher Jara"
  date: "2025-04-10"
  chapters:
    - index.qmd
    - Inscripcion.qmd
    - soccer_amateur.qmd
    - sumo_amateur.qmd
    - linea_amateur.qmd
    - premios_crespibot.qmd
    - llaves_crespibot.qmd
    - ganadores_crespibot.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - superhero
      
  pdf:
    documentclass: scrreprt



