project:
  type: book

book:
  title: "CrespiBot"
  author: "Tec. Sup. Christopher Jara"
  date: "2025-04-10"
  chapters:
    - index.qmd
    - Inscripcion.qmd
    - part: Reglamentos
      chapters:
          - soccer_amateur.qmd
          - sumo_amateur.qmd
          - linea_amateur.qmd
    - premios_crespibot.qmd
    - llaves_crespibot.qmd
    - ganadores_crespibot.qmd
    - references.qmd
  sidebar: 
    Style: "floating"

bibliography: references.bib

format:
  html:
    include-after-body: include-after.html
    toc: true
    toc-title: "Temas a tratar"
    toc-depth: 3
    number-sections: false
    theme:
      - superhero
      
  pdf: default
  docx: default
  epub: default