# Premios entregados durante el CrespiBot

Toda la comunidad Crespiana se siente orgullosa de cada uno de los competidores, quienes participarán en el CrespiBot, ya que todos hemos observado la inmensa motivación, el incansable espíritu de lucha que nos han dejado ver y la inteligencia superior que cada uno ha demostrado, y como no puede ser de otra forma, se entregarán premios tras las mejores participaciones en cada categoría.

## Premio Campeón de Campeones

Para este premio se conciderará todas las participaciones, en concursos de robótica acontecidas en el periodo lectivo 2024 - 2025, incluyendo el CrespiBot, quien acumúle mas puntos, será eñ acreedpr de los siguientes premios:

## Premios para robots seguidores de línea amateur.

Le recomendamos revisar el reglamento.

+-----------------------------------+----------------------------------------------------------------------------------+
| Posición                          | Premio                                                                           |
+===================================+==================================================================================+
| Primer Lugar                      | -   Medalla de campeón del CrespiBot.                                            |
|                                   |                                                                                  |
|                                   | -   Diploma de Reconocimento.                                                    |
|                                   |                                                                                  |
|                                   | -   Cupo directo a TaitaRobot.                                                   |
|                                   |                                                                                  |
|                                   | -   10 en un examen trimestral a su elección, para cada participante del equipo. |
|                                   |                                                                                  |
|                                   | -   10 en un insumo en las materias técnicas, para cada integrante del equipo.   |
+-----------------------------------+----------------------------------------------------------------------------------+
| Segundo Lugar                     | -   Diploma de Reconocimiento.                                                   |
|                                   | -   Cupo directo a TaitaRobot.                                                   |
|                                   | -   10 en un insumo en las materias técnicas, para cada integrante del equipo.   |
+-----------------------------------+----------------------------------------------------------------------------------+
| Tercer Lugar                      | -   Diploma de Reconocimiento.                                                   |
|                                   |                                                                                  |
|                                   | -   10 en un insumo en las materias técnicas, para cada integrante del equipo    |
+-----------------------------------+----------------------------------------------------------------------------------+
| Desde el cuarto lugar en adelante | -   Una nota de 10 en las materias técnicas, para cada integrante del equipo.    |
+-----------------------------------+----------------------------------------------------------------------------------+

***IMPORTANTE:*** deben existir al menos 4 participantes o equipos inscritos, caso contrario se conciderará un evento de exhibición y se entregará un diploma de participación.

## Premios para robots de sumo RC amateur.

Le recomendamos revisar el reglamento.

+---------------+----------------------------------------------------------------------------------+
| Posición      | Premio                                                                           |
+===============+==================================================================================+
| Primer Lugar  | -   Medalla de campeón del CrespiBot.                                            |
|               |                                                                                  |
|               | -   Cupo directo a TaitaRobot.                                                   |
|               |                                                                                  |
|               | -   10 en un examen trimestral a su elección, para cada participante del equipo. |
+---------------+----------------------------------------------------------------------------------+
| Segundo Lugar | -   Diploma de Reconocimiento.                                                   |
|               | -   Cupo directo a TaitaRobot                                                    |
|               | -   10 en un insumo en las materias técnicas, para cada participante del equipo  |
+---------------+----------------------------------------------------------------------------------+
| Tercer Lugar  | -   Diploma de Reconocimiento.                                                   |
|               | -   Cupo directo a TaitaRobot                                                    |
+---------------+----------------------------------------------------------------------------------+

***IMPORTANTE:*** deben existir al menos 4 participantes o equipos inscritos, caso contrario se conciderará un evento de exhibición y se entregará un diploma de participación.

## Premios para robots insecto amateur.

Le recomendamos revisar el reglamento.

+-----------------------------------+-----------------------------------------------+
| Posición                          | Premio                                        |
+===================================+===============================================+
| Primer Lugar                      | -   Medalla de campeón del CrespiBot.         |
|                                   |                                               |
|                                   | -   Diploma de Reconocimento.                 |
|                                   |                                               |
|                                   | -   Cupo directo a TaitaRobot.                |
|                                   |                                               |
|                                   | -   10 en un examen trimestral a su elección. |
|                                   |                                               |
|                                   | -   10 en un insumo en las materias técnicas. |
+-----------------------------------+-----------------------------------------------+
| Segundo Lugar                     | -   Diploma de Reconocimiento.                |
|                                   | -   Cupo directo a TaitaRobot.                |
|                                   | -   10 en un insumo en las materias técnicas. |
+-----------------------------------+-----------------------------------------------+
| Tercer Lugar                      | -   Diploma de Reconocimiento.                |
|                                   |                                               |
|                                   | -   10 en un insumo en las materias técnicas. |
+-----------------------------------+-----------------------------------------------+
| Desde el cuarto lugar en adelante | -   Una nota de 10 en las materias técnicas.  |
+-----------------------------------+-----------------------------------------------+

***IMPORTANTE:*** deben existir al menos 4 participantes o equipos inscritos, caso contrario se conciderará un evento de exhibición y se entregará un diploma de participación.

## Premios para robots soccer amateur (equipos).

Le recomendamos revisar el reglamento.

+-----------------------------------+--------------------------------------------------------------------------------+
| Posición                          | Premio                                                                         |
+===================================+================================================================================+
| Equipo Primer Lugar               | -   2 Medallas de campeón del CrespiBot.                                       |
|                                   |                                                                                |
|                                   | -   2 Diplomas de Reconocimento.                                               |
|                                   |                                                                                |
|                                   | -   2 Cupos directo a TaitaRobot.                                              |
|                                   |                                                                                |
|                                   | -   10 en un examen trimestral a su elección, para cada integrante del equipo. |
|                                   |                                                                                |
|                                   | -   10 en un insumo en las materias técnicas, para cada integrante del equipo. |
+-----------------------------------+--------------------------------------------------------------------------------+
| Segundo Lugar                     | -   2 Diplomas de Reconocimiento.                                              |
|                                   | -   Cupo directo a TaitaRobot                                                  |
|                                   | -   10 en un insumo en las materias técnicas, para cada integrante del equipo. |
+-----------------------------------+--------------------------------------------------------------------------------+
| Tercer Lugar                      | -   Diploma de Reconocimiento.                                                 |
|                                   |                                                                                |
|                                   | -   10 en un insumo en las materias técnicas.                                  |
+-----------------------------------+--------------------------------------------------------------------------------+
| Desde el cuarto lugar en adelante | -   Una nota de 10 en las materias técnicas.                                   |
+-----------------------------------+--------------------------------------------------------------------------------+

***IMPORTANTE:*** deben existir al menos 4 participantes o equipos inscritos, caso contrario se conciderará un evento de exhibición y se entregará un diploma de participación.